version: '3.8'

services:
  flask_ui:
    env_file:
      .env
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./UI:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - PG_HOST=${PG_HOST}
    depends_on:
      - redis
      - timescaledb

  lora_gateway:
    build:
      context: .
      dockerfile: dockerfile.gateway
    env_file:
      .env
    devices:
    - "${SERIAL_PORT}:${SERIAL_PORT}"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - PG_HOST=${PG_HOST}
      - SERIAL_PORT=${SERIAL_PORT}
    depends_on:
      - redis
      - timescaledb

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    env_file:
      .env
    environment:
      - POSTGRES_USER=pond_user
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=pond_data
    volumes:
      - timescale_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  timescale_data:
