"""
PondMonitor Flask Application - Refactored Version

Migrated to use modular services for better maintainability and testability.
Generated by migrate_app.py on 2025-08-18T17:11:30.557796

Week 1 Refactoring Changes:
✅ Centralized configuration management
✅ Database service abstraction with connection pooling
✅ Enhanced error handling and validation
✅ Improved export service with multiple formats
✅ Weather service with intelligent caching
✅ Structured logging with request tracking
✅ Comprehensive unit tests

Original functionality preserved with improved architecture.
"""

import os
import json
import logging
import random
from datetime import datetime, timezone, timedelta
from flask import Flask, render_template, request, jsonify, g
from collections import defaultdict
from typing import Optional, Dict, Any, List

# Import our new modular services (using relative imports)
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from src.config import init_config, get_config
from src.database import init_database, get_database
from src.utils import handle_errors, log_requests, validate_json, Validator
from src.services.export_service import create_export_service, ExportConfig
from src.services.advanced_export_service import AdvancedExportService, AdvancedExportConfig
from src.services.weather_service import create_weather_service
from src.logging_config import setup_logging, get_logger, PerformanceLogger

# Initialize logger
logger = get_logger(__name__)

# Global service instances
db_service = None
export_service = None
advanced_export_service = None
weather_service = None


def create_app(config_file: str = ".env") -> Flask:
    """
    Application factory with dependency injection.
    
    Args:
        config_file: Path to configuration file
    
    Returns:
        Configured Flask application
    """
    global db_service, export_service, advanced_export_service, weather_service
    
    # Initialize configuration
    logger.info("Initializing PondMonitor application")
    config = init_config(config_file)
    
    # Setup logging
    setup_logging(
        config.logging, 
        environment=config.flask.environment,
        enable_request_tracking=True
    )
    
    # Initialize Flask app
    app = Flask(__name__)
    app.config.update({
        'SECRET_KEY': config.flask.secret_key,
        'TESTING': config.flask.testing,
        'DEBUG': config.flask.debug
    })
    
    # Initialize services
    logger.info("Initializing services")
    
    try:
        # Database service
        db_service = init_database(config.database)
        logger.info("✅ Database service initialized")
        
        # Export service
        export_service = create_export_service(db_service)
        logger.info("✅ Export service initialized")
        
        # Advanced export service
        advanced_export_service = AdvancedExportService(db_service)
        logger.info("✅ Advanced export service initialized")
        
        # Weather service
        weather_service = create_weather_service(config.weather, config.redis)
        logger.info("✅ Weather service initialized")
        
        # Alerting services
        from src.services.alert_engine import init_alert_engine
        from src.services.notification_service import init_notification_service
        from src.services.scheduler_service import init_scheduler_service
        
        # Initialize notification service first (required by alert engine)
        notification_service = init_notification_service(config.alerting)
        logger.info("✅ Notification service initialized")
        
        # Initialize alert engine
        alert_engine = init_alert_engine()
        logger.info("✅ Alert engine initialized")
        
        # Initialize scheduler service
        scheduler_service = init_scheduler_service()
        logger.info("✅ Scheduler service initialized")
        
    except Exception as e:
        logger.error(f"Failed to initialize services: {e}")
        raise
    
    # Register error handlers
    register_error_handlers(app)
    
    # Register routes
    register_routes(app)
    
    logger.info("PondMonitor application initialized successfully")
    return app


def register_error_handlers(app: Flask) -> None:
    """Register global error handlers"""
    
    @app.errorhandler(500)
    def internal_server_error(error):
        logger.error(f"Internal server error: {error}")
        return jsonify({"error": "Internal server error"}), 500

    @app.errorhandler(404)
    def not_found_error(error):
        return jsonify({"error": "Resource not found"}), 404


def register_routes(app: Flask) -> None:
    """Register all application routes"""
    
    # =================================================================
    # PAGE ROUTES (unchanged from original)
    # =================================================================
    
    @app.route("/")
    def dashboard():
        return render_template("dashboard.html")

    @app.route("/weather")
    def weather():
        return render_template("weather.html")

    @app.route("/diagnostics")
    def diagnostics():
        return render_template("diagnostics.html")

    @app.route("/export")
    def export():
        return render_template("export.html")
    
    # =================================================================
    # API ROUTES (enhanced with new services)
    # =================================================================
    
    @app.route("/health", endpoint="health_check")
    @log_requests
    @handle_errors
    def health_check():
        """Enhanced health check with service status"""
        
        with PerformanceLogger(logger, "health_check"):
            status = {
                "status": "healthy",
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "services": {}
            }
            
            # Check database service
            try:
                db_health = db_service.health_check()
                status["services"]["database"] = "healthy" if db_health.get("healthy") else "unhealthy"
            except Exception as e:
                logger.warning(f"Database health check failed: {e}")
                status["services"]["database"] = "unhealthy"
            
            # Check weather service
            try:
                weather_health = weather_service.health_check()
                status["services"]["weather_api"] = "healthy" if weather_health.get("healthy") else "degraded"
            except Exception as e:
                logger.warning(f"Weather health check failed: {e}")
                status["services"]["weather_api"] = "unhealthy"
            
            # Overall status
            unhealthy_services = [
                k for k, v in status["services"].items() 
                if v not in ["healthy", "degraded"]
            ]
            
            if unhealthy_services:
                status["status"] = "degraded"
                status["unhealthy_services"] = unhealthy_services
            
            return jsonify(status)
    
    @app.route("/api/status", endpoint="api_status")
    @log_requests
    @handle_errors
    def get_status():
        """Get current sensor status from database"""
        
        with PerformanceLogger(logger, "get_status"):
            # Get latest metrics from database
            latest_metrics = db_service.get_latest_metrics()
            
            if not latest_metrics:
                return jsonify({"error": "No data available"}), 404
            
            # Calculate connection status
            now = datetime.now(timezone.utc)
            if 'station_timestamp' in latest_metrics:
                last_seen = latest_metrics['station_timestamp']
                if isinstance(last_seen, str):
                    last_seen = datetime.fromisoformat(last_seen.replace('Z', '+00:00'))
                
                delta = now - last_seen
                connected = delta.total_seconds() < 120
                last_seen_minutes = int(delta.total_seconds() / 60)
            else:
                connected = False
                last_seen_minutes = 999
            
            # Build response
            response_data = {
                "connected": connected,
                "last_seen_minutes": last_seen_minutes,
                "last_heartbeat": latest_metrics.get('station_timestamp', now.isoformat()),
                "temperature_c": latest_metrics.get('temperature_c'),
                "battery_v": latest_metrics.get('battery_v'),
                "solar_v": latest_metrics.get('solar_v'),
                "signal_dbm": latest_metrics.get('signal_dbm'),
                "on_solar": (latest_metrics.get('solar_v') or 0) > 1.0,
                "device_id": "POND-001",
                "firmware_version": "1.0.0"
            }
            
            return jsonify(response_data)
    
    @app.route("/api/dashboard", endpoint="api_dashboard")
    @log_requests
    @handle_errors
    def api_dashboard():
        """Get dashboard data with enhanced validation"""
        
        start = request.args.get("start")
        end = request.args.get("end")
        
        if not start or not end:
            return jsonify({"error": "Missing start or end parameter"}), 400
        
        try:
            # Validate datetime range using new validator
            start_dt, end_dt = Validator.validate_datetime_range(start, end)
            
            with PerformanceLogger(logger, "dashboard_data_query", 
                                 start=start, end=end):
                
                # Get pond metrics
                pond_data = db_service.get_pond_metrics(start_dt, end_dt)
                
                # Transform to expected format (timestamp in milliseconds, value)
                level_data = []
                outflow_data = []
                
                for record in pond_data:
                    timestamp_ms = int(record['timestamp'].timestamp() * 1000)
                    
                    if record['level_cm'] is not None:
                        level_data.append([timestamp_ms, record['level_cm']])
                    
                    if record['outflow_lps'] is not None:
                        outflow_data.append([timestamp_ms, record['outflow_lps']])
                
                return jsonify({
                    "level": level_data,
                    "outflow": outflow_data,
                    "data_points": len(pond_data)
                })
                
        except Exception as e:
            logger.error(f"Dashboard API error: {e}", exc_info=True)
            raise
    
    @app.route("/api/lora", endpoint="api_lora")
    @log_requests
    @handle_errors
    def diagnostics_data():
        """Get LoRa diagnostics data"""
        
        hours = request.args.get("hours", 24, type=int)
        
        # Validate hours parameter
        if not 1 <= hours <= 168:  # 1 hour to 1 week
            return jsonify({"error": "Hours must be between 1 and 168"}), 400
        
        start_time = datetime.now(timezone.utc) - timedelta(hours=hours)
        end_time = datetime.now(timezone.utc)
        
        with PerformanceLogger(logger, "lora_diagnostics_query", hours=hours):
            
            # Get station metrics
            station_data = db_service.get_station_metrics(start_time, end_time)
            
            # Transform to expected format
            temperature = []
            battery_voltage = []
            solar_voltage = []
            signal_strength = []
            
            for record in station_data:
                timestamp_ms = int(record['timestamp'].timestamp() * 1000)
                
                if record['temperature_c'] is not None:
                    temperature.append([timestamp_ms, round(record['temperature_c'], 1)])
                
                if record['battery_v'] is not None:
                    battery_voltage.append([timestamp_ms, round(record['battery_v'], 2)])
                
                if record['solar_v'] is not None:
                    solar_voltage.append([timestamp_ms, round(record['solar_v'], 2)])
                
                if record['signal_dbm'] is not None:
                    signal_strength.append([timestamp_ms, record['signal_dbm']])
            
            return jsonify({
                "temperature": temperature,
                "battery_voltage": battery_voltage,
                "solar_voltage": solar_voltage,
                "signal_strength": signal_strength,
                "data_points": len(station_data),
                "time_range_hours": hours
            })
    
    # =================================================================
    # WEATHER API ROUTES (using new weather service)
    # =================================================================
    
    @app.route("/api/weather/current", endpoint="weather_current")
    @log_requests
    @handle_errors
    def weather_current():
        """Get current weather conditions"""
        
        with PerformanceLogger(logger, "weather_current"):
            current_weather = weather_service.get_current_weather()
            
            if not current_weather:
                return jsonify({"error": "Weather service unavailable"}), 503
            
            # Transform to expected format
            response = {
                "timestamp": current_weather.timestamp,
                "temperature": current_weather.temperature,
                "pressure": current_weather.pressure,
                "humidity": current_weather.humidity,
                "wind": current_weather.wind_speed,
                "wind_direction": current_weather.wind_direction,
                "wind_gust": current_weather.wind_gust,
                "cloud_coverage": current_weather.cloud_coverage,
                "rain": current_weather.precipitation,
                "symbol_code": current_weather.symbol_code
            }
            
            return jsonify(response)
    
    @app.route("/api/weather/meteogram", endpoint="weather_meteogram")
    @log_requests
    @handle_errors
    def weather_meteogram():
        """Get 48-hour detailed forecast for meteogram"""
        
        with PerformanceLogger(logger, "weather_meteogram"):
            meteogram_data = weather_service.get_meteogram_data(48)
            
            # Transform to expected format
            result = []
            for weather in meteogram_data:
                weather_point = {
                    "time": int(datetime.fromisoformat(weather.timestamp.replace("Z", "+00:00")).timestamp() * 1000),
                    "temperature": weather.temperature,
                    "rain": weather.precipitation,
                    "wind": weather.wind_speed,
                    "wind_direction": weather.wind_direction,
                    "wind_gust": weather.wind_gust,
                    "pressure": weather.pressure,
                    "humidity": weather.humidity,
                    "cloud": weather.cloud_coverage,
                    "symbol_code": weather.symbol_code
                }
                result.append(weather_point)
            
            return jsonify(result)
    
    @app.route("/api/weather/daily", endpoint="weather_daily")
    @log_requests
    @handle_errors
    def daily_forecast():
        """Get 7-day daily forecast summary"""
        
        with PerformanceLogger(logger, "weather_daily"):
            daily_data = weather_service.get_daily_forecast(7)
            
            # Transform to expected format
            result = []
            for day in daily_data:
                daily_summary = {
                    "date": day.date,
                    "temp": day.temp_max,
                    "temp_min": day.temp_min,
                    "temp_avg": day.temp_avg,
                    "wind_avg": day.wind_avg,
                    "wind_gust": day.wind_gust,
                    "rain": day.precipitation,
                    "humidity_avg": day.humidity_avg,
                    "pressure_avg": day.pressure_avg,
                    "icon": day.symbol_code
                }
                result.append(daily_summary)
            
            return jsonify(result)
    
    @app.route("/api/weather/stats", endpoint="weather_stats")
    @log_requests
    @handle_errors
    def weather_stats():
        """Get weather statistics for the last 24 hours"""
        
        with PerformanceLogger(logger, "weather_stats"):
            stats = weather_service.get_weather_statistics(24)
            
            if not stats:
                return jsonify({"error": "Unable to calculate statistics"}), 503
            
            return jsonify(stats.to_dict())
    
    # =================================================================
    # ENHANCED EXPORT ROUTES (using new export service)
    # =================================================================
    
    @app.route("/api/export/formats", endpoint="export_formats")
    @log_requests
    @handle_errors
    def export_formats():
        """Get available export formats"""
        formats = export_service.get_export_formats()
        return jsonify(formats)
    
    @app.route("/api/export/estimate", endpoint="export_estimate")
    @log_requests
    @handle_errors
    def export_estimate():
        """Estimate export size and processing time"""
        
        start = request.args.get("start")
        end = request.args.get("end")
        
        if not start or not end:
            return jsonify({"error": "Missing start or end parameter"}), 400
        
        try:
            start_dt, end_dt = Validator.validate_datetime_range(start, end)
            
            config = ExportConfig(
                start_time=start_dt,
                end_time=end_dt,
                format=request.args.get('format', 'csv')
            )
            
            estimate = export_service.estimate_export_size(config)
            return jsonify(estimate)
            
        except Exception as e:
            logger.error(f"Export estimation error: {e}")
            raise
    
    @app.route("/api/export/<format>", endpoint="export_data")
    @log_requests
    @handle_errors
    def export_data(format: str):
        """Export data in specified format"""
        
        start = request.args.get("start")
        end = request.args.get("end")
        
        if not start or not end:
            return jsonify({"error": "Missing start or end parameter"}), 400
        
        try:
            start_dt, end_dt = Validator.validate_datetime_range(start, end)
            
            config = ExportConfig(
                start_time=start_dt,
                end_time=end_dt,
                format=format,
                include_pond_data=request.args.get('include_pond', 'true').lower() == 'true',
                include_station_data=request.args.get('include_station', 'true').lower() == 'true',
                station_id=request.args.get('station_id'),
                limit=request.args.get('limit', type=int)
            )
            
            with PerformanceLogger(logger, "data_export", 
                                 format=format, start=start, end=end):
                
                exported_data = export_service.export_data(config)
                
                # Set appropriate content type and headers
                if format == 'csv':
                    response = app.response_class(
                        exported_data,
                        mimetype='text/csv',
                        headers={"Content-Disposition": f"attachment; filename=pond_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"}
                    )
                elif format == 'json':
                    response = app.response_class(
                        exported_data,
                        mimetype='application/json',
                        headers={"Content-Disposition": f"attachment; filename=pond_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"}
                    )
                elif format in ['excel', 'xlsx']:
                    response = app.response_class(
                        exported_data,
                        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                        headers={"Content-Disposition": f"attachment; filename=pond_data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"}
                    )
                else:
                    return jsonify({"error": f"Unsupported format: {format}"}), 400
                
                return response
                
        except Exception as e:
            logger.error(f"Export error: {e}")
            raise

    # =================================================================
    # ADVANCED EXPORT ROUTES (Week 2 Enhancement)
    # =================================================================
    
    @app.route("/api/advanced-export/config", endpoint="advanced_export_config")
    @log_requests
    @handle_errors
    def get_advanced_export_config():
        """Get available advanced export configuration options"""
        
        config_options = {
            "data_types": [
                {"id": "pond_data", "name": "Pond Measurements", "description": "Temperature, pH, oxygen levels"},
                {"id": "station_data", "name": "Station Diagnostics", "description": "Battery, signal, solar power"},
                {"id": "weather_data", "name": "Weather Data", "description": "Temperature, humidity, pressure"}
            ],
            "aggregation_options": [
                {"id": "raw", "name": "Raw Data", "description": "All individual measurements"},
                {"id": "hourly", "name": "Hourly Average", "description": "Aggregated by hour"},
                {"id": "daily", "name": "Daily Summary", "description": "Min/max/average per day"}
            ],
            "export_formats": [
                {"id": "excel", "name": "Excel (.xlsx)", "description": "Professional Excel format with charts"},
                {"id": "csv", "name": "CSV", "description": "Comma-separated values"},
                {"id": "json", "name": "JSON", "description": "JavaScript Object Notation"}
            ],
            "filter_ranges": advanced_export_service.get_filter_ranges()
        }
        
        return jsonify(config_options)
    
    @app.route("/api/advanced-export/estimate", methods=["POST"], endpoint="advanced_export_estimate")
    @log_requests
    @handle_errors
    @validate_json(required_fields=['start_time', 'end_time'], optional_fields=['data_types', 'format', 'aggregation'])
    def advanced_export_estimate():
        """Estimate advanced export size and processing time"""
        
        try:
            data = request.get_json()
            
            config = AdvancedExportConfig(
                start_time=datetime.fromisoformat(data['start_time'].replace('Z', '+00:00')),
                end_time=datetime.fromisoformat(data['end_time'].replace('Z', '+00:00')),
                data_types=data.get('data_types', ['pond_data']),
                format=data.get('format', 'excel'),
                aggregation=data.get('aggregation', 'raw'),
                include_charts=data.get('include_charts', False),
                excel_formatting=data.get('excel_formatting', True),
                temperature_range=data.get('temperature_range'),
                battery_range=data.get('battery_range'),
                signal_range=data.get('signal_range')
            )
            
            estimate = advanced_export_service.estimate_export(config)
            return jsonify(estimate)
            
        except Exception as e:
            logger.error(f"Advanced export estimation error: {e}")
            raise
    
    @app.route("/api/advanced-export", methods=["POST"], endpoint="advanced_export")
    @log_requests
    @handle_errors
    @validate_json(required_fields=['start_time', 'end_time'], optional_fields=['data_types', 'format', 'aggregation'])
    def advanced_export():
        """Perform advanced export with enhanced features"""
        
        try:
            data = request.get_json()
            
            config = AdvancedExportConfig(
                start_time=datetime.fromisoformat(data['start_time'].replace('Z', '+00:00')),
                end_time=datetime.fromisoformat(data['end_time'].replace('Z', '+00:00')),
                data_types=data.get('data_types', ['pond_data']),
                format=data.get('format', 'excel'),
                aggregation=data.get('aggregation', 'raw'),
                include_charts=data.get('include_charts', False),
                excel_formatting=data.get('excel_formatting', True),
                temperature_range=data.get('temperature_range'),
                battery_range=data.get('battery_range'),
                signal_range=data.get('signal_range')
            )
            
            with PerformanceLogger(logger, "advanced_export", 
                                 format=config.format, 
                                 data_types=config.data_types,
                                 aggregation=config.aggregation):
                
                exported_data = advanced_export_service.export_advanced(config)
                
                # Generate filename with timestamp and configuration info
                timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
                data_type_suffix = "_".join(config.data_types)
                filename_base = f"pond_advanced_{data_type_suffix}_{config.aggregation}_{timestamp}"
                
                # Set appropriate content type and headers
                if config.format == 'csv':
                    response = app.response_class(
                        exported_data,
                        mimetype='text/csv',
                        headers={"Content-Disposition": f"attachment; filename={filename_base}.csv"}
                    )
                elif config.format == 'json':
                    response = app.response_class(
                        exported_data,
                        mimetype='application/json',
                        headers={"Content-Disposition": f"attachment; filename={filename_base}.json"}
                    )
                elif config.format in ['excel', 'xlsx']:
                    response = app.response_class(
                        exported_data,
                        mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                        headers={"Content-Disposition": f"attachment; filename={filename_base}.xlsx"}
                    )
                else:
                    return jsonify({"error": f"Unsupported format: {config.format}"}), 400
                
                return response
                
        except Exception as e:
            logger.error(f"Advanced export error: {e}")
            raise
    
    @app.route("/api/advanced-export/progress/<job_id>", endpoint="advanced_export_progress")
    @log_requests
    @handle_errors
    def advanced_export_progress(job_id: str):
        """Get progress of long-running advanced export job"""
        
        try:
            progress = advanced_export_service.get_export_progress(job_id)
            return jsonify(progress)
        except Exception as e:
            logger.error(f"Export progress error: {e}")
            raise
    
    # =================================================================
    # LOGS API ENDPOINT
    # =================================================================
    
    @app.route("/api/logs", endpoint="api_logs")
    @log_requests
    @handle_errors
    def get_system_logs():
        """Get system logs for diagnostics"""
        try:
            limit = int(request.args.get('limit', 50))
            limit = min(limit, 200)  # Cap at 200 logs
            
            # Mock logs for now - in a real implementation, this would read from actual log files
            # or a logging database
            logs = [
                {
                    'timestamp': datetime.now().isoformat(),
                    'level': 'INFO',
                    'message': 'System health check completed successfully'
                },
                {
                    'timestamp': (datetime.now() - timedelta(minutes=5)).isoformat(),
                    'level': 'INFO',
                    'message': 'Database connection pool refreshed'
                },
                {
                    'timestamp': (datetime.now() - timedelta(minutes=10)).isoformat(),
                    'level': 'WARNING',
                    'message': 'Signal strength below optimal threshold: -95 dBm'
                },
                {
                    'timestamp': (datetime.now() - timedelta(minutes=15)).isoformat(),
                    'level': 'INFO',
                    'message': 'Weather data cache updated'
                },
                {
                    'timestamp': (datetime.now() - timedelta(minutes=20)).isoformat(),
                    'level': 'ERROR',
                    'message': 'Failed to connect to sensor: timeout after 30s'
                }
            ]
            
            return jsonify(logs[:limit])
            
        except Exception as e:
            logger.error(f"Error fetching system logs: {e}")
            return jsonify([]), 500

    # =================================================================
    # DIAGNOSTIC ACTION ENDPOINTS
    # =================================================================
    
    @app.route("/api/test-connection", methods=["POST"], endpoint="test_connection")
    @log_requests
    @handle_errors
    def test_connection():
        """Test device connection"""
        try:
            # In a real implementation, this would test the actual device connection
            # For now, simulate a connection test
            import random
            import time
            
            time.sleep(1)  # Simulate test duration
            
            success = random.choice([True, True, True, False])  # 75% success rate
            
            if success:
                return jsonify({
                    'success': True,
                    'message': 'Connection test successful',
                    'details': {
                        'response_time_ms': random.randint(50, 200),
                        'signal_strength': random.randint(-95, -60),
                        'packet_loss': random.randint(0, 5)
                    }
                })
            else:
                return jsonify({
                    'success': False,
                    'error': 'Connection timeout - device not responding'
                }), 503
                
        except Exception as e:
            logger.error(f"Connection test error: {e}")
            return jsonify({'success': False, 'error': str(e)}), 500
    
    @app.route("/api/diagnostics/export", endpoint="diagnostics_export")
    @log_requests
    @handle_errors
    def export_diagnostics():
        """Export system diagnostics data"""
        try:
            # Get current status and recent data for diagnostics export
            status_data = {
                'export_timestamp': datetime.now().isoformat(),
                'system_status': {
                    'connected': True,
                    'battery_voltage': 3.8,
                    'signal_strength': -75,
                    'temperature': 22.5,
                    'uptime_seconds': 86400,
                    'free_memory': 2048,
                    'device_id': 'POND_MONITOR_001'
                },
                'recent_measurements': [
                    {'timestamp': (datetime.now() - timedelta(minutes=i*5)).isoformat(), 
                     'temperature': 22.5 + random.uniform(-2, 2),
                     'battery': 3.8 + random.uniform(-0.2, 0.2),
                     'signal': -75 + random.randint(-10, 10)}
                    for i in range(12)  # Last hour of data
                ],
                'system_logs': [
                    {'timestamp': datetime.now().isoformat(), 'level': 'INFO', 'message': 'Diagnostics export generated'},
                    {'timestamp': (datetime.now() - timedelta(minutes=5)).isoformat(), 'level': 'INFO', 'message': 'System health check passed'},
                    {'timestamp': (datetime.now() - timedelta(minutes=10)).isoformat(), 'level': 'WARNING', 'message': 'Signal strength fluctuation detected'}
                ]
            }
            
            return jsonify(status_data)
            
        except Exception as e:
            logger.error(f"Diagnostics export error: {e}")
            return jsonify({'error': 'Failed to generate diagnostics export'}), 500
    
    @app.route("/api/device/reset", methods=["POST"], endpoint="device_reset")
    @log_requests
    @handle_errors
    def reset_device():
        """Reset/restart the monitoring device"""
        try:
            # In a real implementation, this would send a reset command to the device
            # For now, simulate the reset request
            logger.info("Device reset requested via web interface")
            
            return jsonify({
                'success': True,
                'message': 'Device reset command sent successfully',
                'estimated_downtime_minutes': 3
            })
            
        except Exception as e:
            logger.error(f"Device reset error: {e}")
            return jsonify({'error': 'Failed to send reset command'}), 500

    # =================================================================
    # ALERT MANAGEMENT ROUTES
    # =================================================================
    
    @app.route("/alerts", endpoint="alerts_page")
    @log_requests
    @handle_errors
    def alerts_page():
        """Alert configuration and monitoring page"""
        return render_template("alerts.html")
    
    # Alert Rules API
    @app.route("/api/alerts/rules", endpoint="alert_rules_list")
    @log_requests
    @handle_errors
    def get_alert_rules():
        """Get all alert rules"""
        try:
            from src.services.alert_engine import get_alert_engine
            
            alert_engine = get_alert_engine()
            rules = alert_engine.get_active_rules()
            
            # Convert to JSON-serializable format
            rules_data = []
            for rule in rules:
                rules_data.append({
                    'id': rule.id,
                    'name': rule.name,
                    'description': rule.description,
                    'rule_type': rule.rule_type.value,
                    'metric_type': rule.metric_type.value,
                    'station_id': rule.station_id,
                    'conditions': rule.conditions,
                    'severity': rule.severity.value,
                    'enabled': rule.enabled,
                    'channels': rule.channels,
                    'cooldown_minutes': rule.cooldown_minutes,
                    'max_alerts_per_hour': rule.max_alerts_per_hour,
                    'created_at': rule.created_at.isoformat() if rule.created_at else None,
                    'updated_at': rule.updated_at.isoformat() if rule.updated_at else None
                })
            
            return jsonify(rules_data)
            
        except Exception as e:
            logger.error(f"Failed to get alert rules: {e}")
            return jsonify({'error': str(e)}), 500
    
    @app.route("/api/alerts/rules", methods=["POST"], endpoint="create_alert_rule")
    @log_requests
    @handle_errors
    @validate_json({
        'name': {'type': 'string', 'required': True, 'minlength': 1},
        'rule_type': {'type': 'string', 'required': True, 'allowed': ['threshold', 'range', 'rate_of_change', 'missing_data']},
        'metric_type': {'type': 'string', 'required': True, 'allowed': ['water_level', 'temperature', 'battery_voltage', 'signal_strength', 'outflow']},
        'conditions': {'type': 'dict', 'required': True},
        'severity': {'type': 'string', 'required': True, 'allowed': ['info', 'warning', 'critical']}
    })
    def create_alert_rule():
        """Create a new alert rule"""
        try:
            data = request.get_json()
            
            # Create rule in database
            rule_id = str(__import__('uuid').uuid4())
            
            result = db_service.execute_query("""
                INSERT INTO alert_rules 
                (id, name, description, rule_type, metric_type, station_id, conditions, 
                 severity, enabled, channels, cooldown_minutes, max_alerts_per_hour)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """, (
                rule_id,
                data['name'],
                data.get('description', ''),
                data['rule_type'],
                data['metric_type'],
                data.get('station_id'),
                json.dumps(data['conditions']),
                data['severity'],
                data.get('enabled', True),
                json.dumps(data.get('channels', ['email'])),
                data.get('cooldown_minutes', 60),
                data.get('max_alerts_per_hour', 5)
            ), fetch=False)
            
            logger.info(f"Created alert rule: {data['name']} (ID: {rule_id})")
            return jsonify({'id': rule_id, 'message': 'Alert rule created successfully'})
            
        except Exception as e:
            logger.error(f"Failed to create alert rule: {e}")
            return jsonify({'error': str(e)}), 500
    
    @app.route("/api/alerts/rules/<rule_id>", methods=["PUT"], endpoint="update_alert_rule")
    @log_requests
    @handle_errors
    def update_alert_rule(rule_id: str):
        """Update an existing alert rule"""
        try:
            data = request.get_json()
            
            # Build update query dynamically
            update_fields = []
            params = []
            
            for field in ['name', 'description', 'rule_type', 'metric_type', 'station_id', 
                         'severity', 'enabled', 'cooldown_minutes', 'max_alerts_per_hour']:
                if field in data:
                    update_fields.append(f"{field} = %s")
                    params.append(data[field])
            
            if 'conditions' in data:
                update_fields.append("conditions = %s")
                params.append(json.dumps(data['conditions']))
            
            if 'channels' in data:
                update_fields.append("channels = %s")
                params.append(json.dumps(data['channels']))
            
            if not update_fields:
                return jsonify({'error': 'No fields to update'}), 400
            
            update_fields.append("updated_at = NOW()")
            params.append(rule_id)
            
            query = f"UPDATE alert_rules SET {', '.join(update_fields)} WHERE id = %s"
            result = db_service.execute_query(query, tuple(params), fetch=False)
            
            if result.row_count == 0:
                return jsonify({'error': 'Alert rule not found'}), 404
            
            logger.info(f"Updated alert rule: {rule_id}")
            return jsonify({'message': 'Alert rule updated successfully'})
            
        except Exception as e:
            logger.error(f"Failed to update alert rule: {e}")
            return jsonify({'error': str(e)}), 500
    
    @app.route("/api/alerts/rules/<rule_id>", methods=["DELETE"], endpoint="delete_alert_rule")
    @log_requests
    @handle_errors
    def delete_alert_rule(rule_id: str):
        """Delete an alert rule"""
        try:
            result = db_service.execute_query(
                "DELETE FROM alert_rules WHERE id = %s",
                (rule_id,), fetch=False
            )
            
            if result.row_count == 0:
                return jsonify({'error': 'Alert rule not found'}), 404
            
            logger.info(f"Deleted alert rule: {rule_id}")
            return jsonify({'message': 'Alert rule deleted successfully'})
            
        except Exception as e:
            logger.error(f"Failed to delete alert rule: {e}")
            return jsonify({'error': str(e)}), 500
    
    # Active Alerts API
    @app.route("/api/alerts/active", endpoint="active_alerts_list")
    @log_requests
    @handle_errors
    def get_active_alerts():
        """Get all active alerts"""
        try:
            from src.services.alert_engine import get_alert_engine
            
            alert_engine = get_alert_engine()
            station_id = request.args.get('station_id')
            
            active_alerts = alert_engine.get_active_alerts(station_id)
            
            alerts_data = []
            for alert in active_alerts:
                alerts_data.append({
                    'id': alert.id,
                    'rule_id': alert.rule_id,
                    'severity': alert.severity.value,
                    'metric_type': alert.metric_type.value,
                    'station_id': alert.station_id,
                    'triggered_at': alert.triggered_at.isoformat(),
                    'trigger_value': alert.trigger_value,
                    'threshold_value': alert.threshold_value,
                    'message': alert.message,
                    'status': alert.status.value,
                    'acknowledged_at': alert.acknowledged_at.isoformat() if alert.acknowledged_at else None,
                    'acknowledged_by': alert.acknowledged_by,
                    'notifications_sent': alert.notifications_sent
                })
            
            return jsonify(alerts_data)
            
        except Exception as e:
            logger.error(f"Failed to get active alerts: {e}")
            return jsonify({'error': str(e)}), 500
    
    @app.route("/api/alerts/<alert_id>/acknowledge", methods=["POST"], endpoint="acknowledge_alert")
    @log_requests
    @handle_errors
    def acknowledge_alert(alert_id: str):
        """Acknowledge an active alert"""
        try:
            from src.services.alert_engine import get_alert_engine
            
            data = request.get_json() or {}
            acknowledged_by = data.get('acknowledged_by', 'user')
            
            alert_engine = get_alert_engine()
            success = alert_engine.acknowledge_alert(alert_id, acknowledged_by)
            
            if success:
                logger.info(f"Alert {alert_id} acknowledged by {acknowledged_by}")
                return jsonify({'message': 'Alert acknowledged successfully'})
            else:
                return jsonify({'error': 'Alert not found or already acknowledged'}), 404
                
        except Exception as e:
            logger.error(f"Failed to acknowledge alert: {e}")
            return jsonify({'error': str(e)}), 500
    
    @app.route("/api/alerts/<alert_id>/resolve", methods=["POST"], endpoint="resolve_alert")
    @log_requests
    @handle_errors
    def resolve_alert(alert_id: str):
        """Resolve an alert"""
        try:
            from src.services.alert_engine import get_alert_engine
            
            data = request.get_json() or {}
            resolved_by = data.get('resolved_by', 'user')
            
            alert_engine = get_alert_engine()
            success = alert_engine.resolve_alert(alert_id, resolved_by)
            
            if success:
                logger.info(f"Alert {alert_id} resolved by {resolved_by}")
                return jsonify({'message': 'Alert resolved successfully'})
            else:
                return jsonify({'error': 'Alert not found or already resolved'}), 404
                
        except Exception as e:
            logger.error(f"Failed to resolve alert: {e}")
            return jsonify({'error': str(e)}), 500
    
    # Alert Statistics and History
    @app.route("/api/alerts/statistics", endpoint="alert_statistics")
    @log_requests
    @handle_errors
    def get_alert_statistics():
        """Get alert statistics and engine status"""
        try:
            from src.services.alert_engine import get_alert_engine
            
            alert_engine = get_alert_engine()
            stats = alert_engine.get_statistics()
            
            return jsonify(stats)
            
        except Exception as e:
            logger.error(f"Failed to get alert statistics: {e}")
            return jsonify({'error': str(e)}), 500
    
    @app.route("/api/alerts/history", endpoint="alert_history")
    @log_requests
    @handle_errors
    def get_alert_history():
        """Get alert history with filters"""
        try:
            # Parse query parameters
            hours = int(request.args.get('hours', 24))
            severity = request.args.get('severity')
            station_id = request.args.get('station_id')
            status = request.args.get('status')
            limit = int(request.args.get('limit', 100))
            
            # Build query
            query = """
                SELECT id, rule_id, severity, metric_type, station_id, triggered_at,
                       trigger_value, threshold_value, message, status,
                       acknowledged_at, acknowledged_by, resolved_at, resolved_by
                FROM alert_history
                WHERE triggered_at > %s
            """
            params = [datetime.now(timezone.utc) - timedelta(hours=hours)]
            
            if severity:
                query += " AND severity = %s"
                params.append(severity)
            
            if station_id:
                query += " AND station_id = %s"
                params.append(station_id)
            
            if status:
                query += " AND status = %s"
                params.append(status)
            
            query += " ORDER BY triggered_at DESC LIMIT %s"
            params.append(limit)
            
            result = db_service.execute_query(query, tuple(params))
            
            history_data = []
            for row_dict in result.to_dict_list():
                history_data.append({
                    'id': row_dict['id'],
                    'rule_id': row_dict['rule_id'],
                    'severity': row_dict['severity'],
                    'metric_type': row_dict['metric_type'],
                    'station_id': row_dict['station_id'],
                    'triggered_at': row_dict['triggered_at'].isoformat(),
                    'trigger_value': row_dict['trigger_value'],
                    'threshold_value': row_dict['threshold_value'],
                    'message': row_dict['message'],
                    'status': row_dict['status'],
                    'acknowledged_at': row_dict['acknowledged_at'].isoformat() if row_dict['acknowledged_at'] else None,
                    'acknowledged_by': row_dict['acknowledged_by'],
                    'resolved_at': row_dict['resolved_at'].isoformat() if row_dict['resolved_at'] else None,
                    'resolved_by': row_dict['resolved_by']
                })
            
            return jsonify(history_data)
            
        except Exception as e:
            logger.error(f"Failed to get alert history: {e}")
            return jsonify({'error': str(e)}), 500
    
    # Notification Status
    @app.route("/api/alerts/notifications/status", endpoint="notification_status")
    @log_requests
    @handle_errors
    def get_notification_status():
        """Get notification service status"""
        try:
            from src.services.notification_service import get_notification_service
            
            notification_service = get_notification_service()
            status = notification_service.get_channel_status()
            
            return jsonify(status)
            
        except Exception as e:
            logger.error(f"Failed to get notification status: {e}")
            return jsonify({'error': str(e)}), 500
    
    @app.route("/api/alerts/notifications/browser", methods=["GET"], endpoint="browser_notifications")
    @log_requests
    @handle_errors
    def get_browser_notifications():
        """Get browser notifications from Redis"""
        try:
            import redis
            import json
            
            r = redis.Redis(**config.redis.get_connection_dict())
            
            # Get notifications from Redis
            notifications_raw = r.lrange('browser_notifications', 0, -1)
            notifications = []
            
            for notif_raw in notifications_raw:
                try:
                    notification = json.loads(notif_raw.decode('utf-8'))
                    notifications.append(notification)
                except Exception as parse_error:
                    logger.warning(f"Failed to parse browser notification: {parse_error}")
            
            return jsonify({
                'notifications': notifications,
                'count': len(notifications)
            })
            
        except Exception as e:
            logger.error(f"Failed to get browser notifications: {e}")
            return jsonify({'error': str(e), 'notifications': [], 'count': 0}), 500

    @app.route("/api/alerts/notifications/browser/mark-read", methods=["POST"], endpoint="mark_notifications_read")
    @log_requests
    @handle_errors
    def mark_notifications_read():
        """Mark browser notifications as read"""
        try:
            import redis
            
            data = request.get_json() or {}
            notification_ids = data.get('notification_ids', [])
            
            if not notification_ids:
                return jsonify({'success': True, 'message': 'No notifications to mark'})
            
            r = redis.Redis(**config.redis.get_connection_dict())
            
            # For now, we'll just acknowledge the request
            # In a more sophisticated system, we'd track read status per user/session
            return jsonify({
                'success': True, 
                'message': f'Marked {len(notification_ids)} notifications as read'
            })
            
        except Exception as e:
            logger.error(f"Failed to mark notifications as read: {e}")
            return jsonify({'error': str(e)}), 500

    @app.route("/api/alerts/notifications/test", methods=["POST"], endpoint="test_notifications")
    @log_requests
    @handle_errors
    def test_notifications():
        """Send test notification to verify configuration"""
        try:
            from src.services.notification_service import get_notification_service, NotificationMessage
            import asyncio
            
            data = request.get_json() or {}
            channels = data.get('channels', ['email'])
            
            message = NotificationMessage(
                title="PondMonitor Test Alert",
                message="This is a test notification from the PondMonitor alerting system. If you receive this message, your notification configuration is working correctly.",
                severity="info",
                timestamp=datetime.now(timezone.utc),
                include_chart=False
            )
            
            notification_service = get_notification_service()
            results = asyncio.run(notification_service.send_alert(message, channels))
            
            # Format results
            results_data = []
            for result in results:
                results_data.append({
                    'channel': result.channel,
                    'recipient': result.recipient,
                    'success': result.success,
                    'error': result.error,
                    'sent_at': result.sent_at.isoformat() if result.sent_at else None
                })
            
            logger.info(f"Test notifications sent: {len(results_data)} attempts")
            return jsonify({'results': results_data})
            
        except Exception as e:
            logger.error(f"Failed to send test notifications: {e}")
            return jsonify({'error': str(e)}), 500

    @app.route("/api/alerts/test-browser-notification", methods=["POST"], endpoint="test_browser_notification")
    @log_requests
    @handle_errors  
    def test_browser_notification():
        """Generate a test browser notification for development/testing"""
        try:
            import redis
            import json
            from datetime import datetime, timezone
            
            # Generate test notification data
            test_notification = {
                'type': 'alert',
                'severity': 'warning',
                'title': 'Test Browser Notifikace',
                'message': 'Toto je testovací notifikace pro ověření funkcionality browser notifikačního systému.',
                'timestamp': datetime.now(timezone.utc).isoformat(),
                'station_id': 'test_station_001',
                'metric_type': 'water_level',
                'trigger_value': 150.5,
                'threshold_value': 140.0,
                'alert_id': f'test_alert_{int(datetime.now().timestamp())}'
            }
            
            # Store in Redis for browser polling
            r = redis.Redis(**config.redis.get_connection_dict())
            r.lpush('browser_notifications', json.dumps(test_notification, default=str))
            r.ltrim('browser_notifications', 0, 99)
            r.expire('browser_notifications', 3600)
            
            logger.info("Test browser notification generated successfully")
            return jsonify({
                'success': True,
                'message': 'Test browser notification generated',
                'notification': test_notification
            })
            
        except Exception as e:
            logger.error(f"Failed to generate test browser notification: {e}")
            return jsonify({'error': str(e)}), 500


# Application factory
app = create_app()

if __name__ == "__main__":
    config = get_config()
    
    # Log startup information
    logger.info("Starting PondMonitor application")
    logger.info(f"Configuration summary: {config.get_summary()}")
    
    # Run application
    # In Docker containers, always use port 5000 internally
    # External port mapping is handled by docker-compose.yml
    import socket
    is_docker = os.path.exists('/.dockerenv')
    port = 5000 if is_docker else config.flask.port
    
    logger.info(f"Running Flask app on {'Docker' if is_docker else 'host'} port {port}")
    app.run(
        host=config.flask.host,
        port=port,
        debug=config.flask.debug
    )
